### PR TITLE
Extended Apple Sensors (SMC)

### PR DESCRIPTION
**Pull request by perfaram**
So, I extended the AppleSensors add-on (and changed its directory name). Complete list : 
* Fixed AppleLMU to use new functions (no more deprecated ones)
* getXXXTemperature, for the CPU, GPU, Palm Area, Battery, Platform Hub Controller, Power board, and RAM sensors
* Tests for these
* Prefixed LMU functions with LMU, SMC, with SMC (no conflicts)

### CODE REVIEW

**Comment by perfaram** [comment]
*All of this comes from my work on @fmorrow's SMCWrapper*

**Comment by perfaram** [comment]
Thanks !

**Comment by PedroBatista** [comment]
Hi, unfortunately we now can't build Io in Linux, probably because of this Addon:

CMake Error at addons/AppleSensors/CMakeLists.txt:28 (message):
  IOKit not found


in Line 28:

find_library(IOKIT IOKit)
if (NOT IOKIT)
    message(FATAL_ERROR "IOKit not found")
endif()


Is there a way to do "cmake .." and having it ignore some addons (like this one) ?

**Comment by perfaram** [comment]
I don't really know how this build system works... You'd better ask @stevedekorte himself, as he uses it more than me :+1:

**Comment by PedroBatista** [comment]
Found the correct way:

To make cmake ignore a particular addon just comment the name in addons/CMakeLists.txt
For this case: # add_subdirectory(AppleSensors)

**Comment by stevedekorte** [comment]
Pedro, thanks for looking into it. I'd be happy to pull that patch.

**Pull request merged**
