### PR TITLE
Feature recentInChain

### PR DESCRIPTION
**Pull request by ghost**
This is a system to allow the convenient handling of coros.
It adresses a problem where stopping and resuming a coroutine by directly accessing it would fail, because it has produced a child and is not actually running.
This is the case for calling on the actorCoroutine while the actor is executing a method, when the coroutine is currently in exception handling code or when the stack of a coro has become to large.

Usage is as follows.

```
o := Object clone

o l := method(
    j := 1
    loop(
        writeln("object: " .. j)
        if( j%2==0, "object will pause now\n" print;pause) //will access the actorCoro offspring implicitly through currentCoroutine
        j = j + 1
    )
)

run := method(
    o @@l

    for(i,1,4,
    yield
        writeln("i: " .. i)
        if(i==2, o actorCoroutine recentInChain resumeLater; "\nobject should resume now\n" print) //here its resumed explicitly
    )

    return nil
)

run
```

### CODE REVIEW

**Comment by stevedekorte** [comment]
thanks for the request but github says it can't automerge - could you fix this and make another request? Thanks

**Comment by MrMormon** [comment]
I guess not.

**Comment by stevedekorte** [comment]
I'd welcome anyone else's attempt at a automerge-able patch. I'd do it myself but I have limited time these day.

**Comment by chaipanya** [comment]
Hi, 
i found convert utf8 function c in your source  "usc2.c","utf8.c"  but i don't understand to use.
Have you example code for test this function.

thank you

**Comment by stevedekorte** [comment]
Chaipanya,  

You can find info on using string encodings in Io here:
http://iolanguage.org/guide/guide.html#Unicode-Sequences

**Comment by ales-tsurko** [comment]
https://github.com/IoLanguage/io/pull/449

**Pull request closed without merging**
