### PR TITLE
Left-hand of assign operator can be an arbitrary message

### PR DESCRIPTION
**Pull request by piotrklibert**

### CODE REVIEW

**Comment by stevedekorte** [comment]
Hi Piotr, thanks for the pull request. Did you test this pretty well? I haven't spotted any issues in scanning it - just asking because I don't have time to test it myself right now.

**Comment by stevedekorte** [comment]
Enjoyed your article on your Io project - nice work!

https://klibert.pl/posts/adding_destructuring_bind_to_io.html

**Comment by piotrklibert** [comment]
About tests: not yet - I only have the example code shown in the post for now. I would like to contribute a more advanced version (recursive and with Map support) of `<-`/`destructure` to Io and I will add tests to `tests/correctness/` then. I also plan to finally get back to my PyParsing port (and later to my MUD implementation), which will use the feature extensively.

About the post: I'm glad you liked it :) I still have some work to do on it - one of my reviewers said that the last two sections were too focused on negatives and that I should rewrite it if I want to convince anyone to give Io a try. It wasn't my intention to focus on negatives, I was just writing the end sections in a hurry - I'll try revising it over the weekend!

Thanks for reviewing&merging - and thanks for creating Io! :) I'm not sure how much, but I'll do my best to also contribute in the future.

**Comment by zephyrtronium** [comment]
I haven't tested and might be misunderstanding, but reading the code makes it look like this patch is creating several copies of every message in the current block after this syntax is encountered. In the worst case, a large script that opens with this type of assignment could smash the stack from the depth of recursion in `IoMessage_deepCopyOf_`, prior to execution even beginning. If that doesn't occur, then we still get copies of every message starting from the message preceding the operator, again from the message following it, and once again from the message following that one.

I'm also understanding that the patch seems to assume that only one message will follow the operator as the value, so `data(i, j) = Number constants pi` will parse into `updateSlot(data(i, j), Number) constants pi`, for example. A later portion of the function specifically scans forward to find the next terminator, which this would need to do as well.

**Pull request merged**
